/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'model' : IDL.Text,
  'vehicleType' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'transmission' : IDL.Text,
  'fuelType' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getModels' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getVehicleTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getYears' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'searchVehicles' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'model' : IDL.Text,
    'vehicleType' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'transmission' : IDL.Text,
    'fuelType' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getModels' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getVehicleTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getYears' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'searchVehicles' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };